const courses = [
  {
    id: 1,
    title: "Lập trình Web Frontend",
    price: 1290000,
    rating: 3,
    description: "web frontend.fdgvfdgfdgdffđggvfdgvfdvdfvdfvdfvdfvdfvdfgvdf",
    image: "/api/placeholder/400/300",
    category_id: 4,
  },
  {
    id: 2,
    title: "React.js Nâng cao",
    price: 1490000,
    rating: 5,
    description: "web frontend.fdgvfdgfdgdffđggvfdgvfdvdfvdfvdfvdfvdfvdfgvdf",
    image: "/api/placeholder/400/300",
    category_id: 5,
  },
  {
    id: 3,
    title: "UX/UI Design Master",
    price: 1790000,
    rating: 4.9,
    description: "web frontend.fdgvfdgfdgdffđggvfdgvfdvdfvdfvdfvdfvdfvdfgvdf",
    image: "/api/placeholder/400/300",
    category_id: 2,
  },
  {
    id: 4,
    title: "Node.js Backend",
    price: 1890000,
    rating: 4.7,
    description: "web frontend.fdgvfdgfdgdffđggvfdgvfdvdfvdfvdfvdfvdfvdfgvdf",
    image: "/api/placeholder/400/300",
    category_id: 6,
  },
  {
    id: 5,
    title: "Python cho AI",
    price: 2190000,
    rating: 4.7,
    description: "web frontend.fdgvfdgfdgdffđggvfdgvfdvdfvdfvdfvdfvdfvdfgvdf",
    image: "/api/placeholder/400/300",
    category_id: 9,
  },
  {
    id: 6,
    title: "DevOps Cơ bản",
    price: 1990000,
    rating: 4.8,
    description: "web frontend.fdgvfdgfdgdffđggvfdgvfdvdfvdfvdfvdfvdfvdfgvdf",
    image: "/api/placeholder/400/300",
    category_id: 11,
  },
  {
    id: 7,
    title: "Lập trình Web Frontend nâng cao",
    price: 2109050,
    rating: 4.5,
    description: "web frontend.fdgvfdgfdgdffđggvfdgvfdvdfvdfvdfvdfvdfvdfgvdf",
    image: "/api/placeholder/400/300",
    category_id: 4,
  },
  {
    id: 8,
    title: "Lập trình Web Frontend pro",
    price: 2190000,
    rating: 4.5,
    description: "web frontend.fdgvfdgfdgdffđggvfdgvfdvdfvdfvdfvdfvdfvdfgvdf",
    image: "/api/placeholder/400/300",
    category_id: 4,
  },
  {
    id: 9,
    title: "Khóa học Vue 3 & Tailwind CSS từ cơ bản đến nâng cao",
    price: 2190000,
    rating: 4.5,
    description:
      "Học cách xây dựng ứng dụng web hiện đại với Vue 3 và Tailwind CSS",
    fullDescription:
      "Khóa học này sẽ giúp bạn làm chủ Vue 3 và Tailwind CSS thông qua việc xây dựng các dự án thực tế. Bạn sẽ học được cách sử dụng Composition API, Reactive References, và các tính năng mới nhất của Vue 3 kết hợp với framework CSS mạnh mẽ Tailwind.",
    image: "/api/placeholder/400/300",
    category_id: 4,
    create_by: 1,
  },
];
export default courses;
